    soundTitles = {
        0  : "Dog",
        1  : "Rooster",
        2  : "Pig",
        3  : "Cow",
        4  : "Frog",
        5  : "Cat",
        6  : "Hen",
        7  : "Insects",
        8  : "Sheep",
        9  : "Crow",
        10 : "Rain",
        11 : "Sea Waves",
        12 : "Crackling Fire",
        13 : "Crickets",
        14 : "Chirping Birds",
        15 : "Water Drops",
        16 : "Wind",
        17 : "Pouring Water",
        18 : "Toilet Flush",
        19 : "Thunderstorm",
        20 : "Crying Baby",
        21 : "Sneezing",
        22 : "Clapping",
        23 : "Breathing",
        24 : "Coughing",
        25 : "Footsteps",
        26 : "Laughing",
        27 : "Brushing Teeth",
        28 : "Snoring",
        29 : "Drinking or Sipping",
        30 : "Knock on Wood Door",
        31 : "Mouse Click",
        32 : "Keyboard Typing",
        33 : "Creaking Wood Door",
        34 : "Can Opening",
        35 : "Washing Machine",
        36 : "Vacuum Cleaner",
        37 : "Clock Alarm",
        38 : "Clock Tick",
        39 : "Glass Breaking",
        40 : "Helicopter",
        41 : "Chainsaw",
        42 : "Siren",
        43 : "Car Horn",
        44 : "Engine",
        45 : "Train",
        46 : "Church Bells",
        47 : "Airplane",
        48 : "Fireworks",
        49 : "Handsaw"
    }